import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  general: [
    'intro',
    {
      type: 'category',
      label: 'Temeller',
      items: [{type: 'autogenerated', dirName: '01-foundations'}],
    },
    {
      type: 'category',
      label: 'Mimari',
      items: [{type: 'autogenerated', dirName: '02-architecture'}],
    },
    {
      type: 'category',
      label: 'Kurulum Baseline',
      items: [{type: 'autogenerated', dirName: '03-installation-common'}],
    },
    {
      type: 'category',
      label: 'Uretim Oncesi',
      items: [{type: 'autogenerated', dirName: '10-production-readiness'}],
    },
  ],
  technical: [
    'technical/overview',
    {
      type: 'category',
      label: 'Dagitimlar',
      items: [
        {type: 'autogenerated', dirName: '04-ubuntu'},
        {type: 'autogenerated', dirName: '05-centos'},
        {type: 'autogenerated', dirName: '06-rhel'},
        {type: 'autogenerated', dirName: '07-rocky-alma'},
      ],
    },
    {
      type: 'category',
      label: 'Guvenlik',
      items: [{type: 'autogenerated', dirName: '08-security'}],
    },
    {
      type: 'category',
      label: 'Operasyon',
      items: [{type: 'autogenerated', dirName: '09-operations'}],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      items: [{type: 'autogenerated', dirName: '15-troubleshooting'}],
    },
  ],
  commands: [{type: 'autogenerated', dirName: '13-commands'}],
  resources: [{type: 'autogenerated', dirName: '14-resources'}],
};

export default sidebars;
